FROM node:lts-alpine

ENV NODE_ENV=development
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

CMD ["sh", "-c", "npm run dev -- --host 0.0.0.0 --port ${VITE_DEV_SERVER_PORT:-5173}"]
